version: '3.9'

services:

  jenkins:
    container_name: ${JENKINS_NAME}
    build:
      context: .
      args:
        TAG: ${JENKINS_TAG}
    restart: always
    networks:
      - default
    ports:
      - ${JENKINS_EXTERNAL_HTTP_PORT_NUMBER}:${JENKINS_HTTP_PORT_NUMBER}
      - ${JENKINS_EXTERNAL_HTTPS_PORT_NUMBER}:${JENKINS_HTTPS_PORT_NUMBER}
    environment:
      ENV: ${ENV}
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      JENKINS_USERNAME: ${JENKINS_USERNAME}
      JENKINS_PASSWORD: ${JENKINS_PASSWORD}
      JENKINS_EMAIL: ${JENKINS_EMAIL}
      JENKINS_HOME: ${JENKINS_HOME}
      JENKINS_HTTP_PORT_NUMBER: ${JENKINS_HTTP_PORT_NUMBER}
      JENKINS_HTTPS_PORT_NUMBER: ${JENKINS_HTTPS_PORT_NUMBER}
      JENKINS_EXTERNAL_HTTP_PORT_NUMBER: ${JENKINS_EXTERNAL_HTTP_PORT_NUMBER}
      JENKINS_EXTERNAL_HTTPS_PORT_NUMBER: ${JENKINS_EXTERNAL_HTTPS_PORT_NUMBER}
      JENKINS_JNLP_PORT_NUMBER: ${JENKINS_JNLP_PORT_NUMBER}
      JENKINS_ENABLE_HTTPS: ${JENKINS_ENABLE_HTTPS}
      JENKINS_SKIP_BOOTSTRAP: ${JENKINS_SKIP_BOOTSTRAP}
      JAVA_OPTS: ${JAVA_OPTS}
